import { ForbiddenException, Injectable, UnauthorizedException } from '@nestjs/common';
import { InjectDataSource, InjectRepository } from '@nestjs/typeorm';
import { DataSource, EntityTarget, ObjectLiteral, Repository } from 'typeorm';
import { NumberingSeries } from '../settings/entities/numbering-series.entity';
import { User } from '../users/entities/user.entity';

// Parties / master data
import { Customer } from '../parties/customers/entities/customer.entity';
import { Supplier } from '../parties/suppliers/entities/supplier.entity';
import { SalesRepresentative } from '../parties/entities/sales-representative.entity';

// Inventory
import { Product } from '../inventory/products/entities/product.entity';
import { ProductBatch } from '../inventory/products/entities/product-batch.entity';
import { StockLevel } from '../inventory/stock-movements/entities/stock-level.entity';
import { StockMovement } from '../inventory/stock-movements/entities/stock-movement.entity';
import { StockAdjustment, StockAdjustmentLine } from '../inventory/stock-movements/entities/stock-adjustment.entity';
import { StockTransfer, StockTransferLine } from '../inventory/stock-movements/entities/stock-transfer.entity';
import { PurchaseReceipt } from '../inventory/stock-movements/entities/purchase-receipt.entity';
import { Warehouse } from '../settings/entities/warehouse.entity';

// Sales
import { Quotation, QuotationLine } from '../sales/quotations/entities/quotation.entity';
import { SalesOrder, SalesOrderLine, DeliveryNote } from '../sales/sales-orders/entities/sales-order.entity';
import {
  SalesInvoice,
  SalesInvoiceLine,
  SalesReturn,
  SalesReturnLine,
} from '../sales/sales-invoices/entities/sales-invoice.entity';
import { SalesPayment } from '../sales/sales-payments/entities/sales-payment.entity';

// Purchasing (scaffold)
import {
  PurchaseRequest,
  PurchaseRequestLine,
  PurchaseOrder,
  PurchaseOrderLine,
  GoodsReceipt,
  PurchaseInvoice,
  PurchaseInvoiceLine,
  PurchasePayment,
  SupplierReturn,
} from '../purchasing/entities/purchasing.entity';

// Treasury
import { CashBox, BankAccount, CashTransaction, Transfer } from '../treasury/entities/treasury.entity';
import { CashMovement } from '../treasury/entities/cash-movement.entity';
import { RecurringExpense } from '../treasury/entities/recurring-expense.entity';

// Imports
import { ImportCargoItem } from '../imports/entities/import-cargo-item.entity';
import { Shipment } from '../imports/entities/shipment.entity';
import { ShipmentExpense } from '../imports/entities/shipment-expense.entity';

// Accounting (scaffold)
import { CostCenter, Project, Budget } from '../accounting/cost-centers/entities/cost-center.entity';

// Audit trail generated by demo usage — cleared along with the data it describes.
import { AuditLog } from '../audit-log/entities/audit-log.entity';

/**
 * Every table a factory reset clears. Deliberately excludes configuration (Company, Branch,
 * Currency, ExchangeRate, Tax, FiscalYear, ProductCategory, Brand, Unit, PackageType,
 * ExpenseCategory, Partner, ShippingExpenseType) and every login (User, Role, Permission,
 * Session) — only NumberingSeries is touched, and only its running counter (see factoryReset()
 * below), never the series definition itself.
 */
const TRANSACTIONAL_ENTITIES: EntityTarget<ObjectLiteral>[] = [
  Customer,
  Supplier,
  SalesRepresentative,
  Product,
  ProductBatch,
  StockLevel,
  StockMovement,
  StockAdjustment,
  StockAdjustmentLine,
  StockTransfer,
  StockTransferLine,
  PurchaseReceipt,
  Warehouse,
  Quotation,
  QuotationLine,
  SalesOrder,
  SalesOrderLine,
  DeliveryNote,
  SalesInvoice,
  SalesInvoiceLine,
  SalesReturn,
  SalesReturnLine,
  SalesPayment,
  PurchaseRequest,
  PurchaseRequestLine,
  PurchaseOrder,
  PurchaseOrderLine,
  GoodsReceipt,
  PurchaseInvoice,
  PurchaseInvoiceLine,
  PurchasePayment,
  SupplierReturn,
  CashBox,
  BankAccount,
  CashTransaction,
  Transfer,
  CashMovement,
  RecurringExpense,
  ImportCargoItem,
  Shipment,
  ShipmentExpense,
  CostCenter,
  Project,
  Budget,
  AuditLog,
];

@Injectable()
export class SystemService {
  constructor(
    @InjectDataSource() private readonly dataSource: DataSource,
    @InjectRepository(User) private readonly userRepo: Repository<User>,
  ) {}

  /**
   * Wipes every transactional/demo-master-data table back to empty in one transaction, keeping
   * configuration and every login untouched. TRUNCATE ... CASCADE resolves foreign-key ordering
   * automatically, so TRANSACTIONAL_ENTITIES above doesn't need to be dependency-sorted by hand.
   *
   * Gated by two layers:
   *  1. @Permissions('system.delete') on the controller (global RBAC — only Administrator has it).
   *  2. Here: the caller's role is re-checked directly against isSystemRole, so a factory reset
   *     can never succeed just because *some* role was later granted the permission string — it
   *     must be the actual protected Administrator/Super-Admin role.
   *
   * Confirmation step: a fixed reset code ('0145'), checked directly rather than against the
   * caller's real account password/argon2 hash — an explicit, deliberate choice made after being
   * warned this means anyone who reads this source knows the code for every deployment, forever,
   * independent of any admin's real password or its rotation. Do not "fix" this back to real
   * password verification without the same conversation happening again.
   */
  async factoryReset(userId: string, resetCode: string): Promise<{ success: true; clearedTables: string[] }> {
    const RESET_CODE = '0145';

    const user = await this.userRepo.findOne({ where: { id: userId }, relations: ['roles'] });
    if (!user) throw new UnauthorizedException('User not found');

    const isSuperAdmin = user.roles?.some((role) => role.isSystemRole);
    if (!isSuperAdmin) {
      throw new ForbiddenException('Only the Administrator / Super Admin role can perform a factory reset');
    }

    if (resetCode !== RESET_CODE) {
      throw new UnauthorizedException('Incorrect reset code');
    }

    return this.dataSource.transaction(async (manager) => {
      const tableNames = TRANSACTIONAL_ENTITIES.map(
        (entity) => manager.getRepository(entity).metadata.tableName,
      );
      const quotedNames = tableNames.map((name) => `"${name}"`).join(', ');
      await manager.query(`TRUNCATE TABLE ${quotedNames} RESTART IDENTITY CASCADE`);

      // Numbering series definitions (prefix/padding/reset period) stay — only the running
      // counter restarts, so the next document recorded after a reset really is number 1 again.
      const seriesRepo = manager.getRepository(NumberingSeries);
      const allSeries = await seriesRepo.find();
      for (const series of allSeries) {
        series.nextNumber = series.startNumber ?? 1;
        series.lastResetKey = null;
      }
      if (allSeries.length) await seriesRepo.save(allSeries);

      return { success: true as const, clearedTables: tableNames };
    });
  }
}
