import { ForbiddenException, Injectable, UnauthorizedException } from '@nestjs/common';
import { InjectDataSource, InjectRepository } from '@nestjs/typeorm';
import { DataSource, EntityTarget, ObjectLiteral, Repository } from 'typeorm';
import { NumberingSeries } from '../settings/entities/numbering-series.entity';
import { User } from '../users/entities/user.entity';

// Parties — SupplierPayment is a payment voucher (transactional); Customer/Supplier/
// SalesRepresentative/CommissionException are the stakeholder master records themselves and
// must survive a reset untouched.
import { SupplierPayment } from '../parties/suppliers/entities/supplier-payment.entity';

// Inventory — Product/ProductCategory/Brand/Unit/PackageType/Warehouse are catalog & branch
// master data and stay; only the stock actually held (StockLevel) and every movement/adjustment/
// audit/transfer/receipt that produced it are cleared, which is what "reset warehouse balances
// to 0" means in practice — the warehouse row itself is untouched.
import { ProductBatch } from '../inventory/products/entities/product-batch.entity';
import { StockLevel } from '../inventory/stock-movements/entities/stock-level.entity';
import { StockMovement } from '../inventory/stock-movements/entities/stock-movement.entity';
import { StockAdjustment, StockAdjustmentLine } from '../inventory/stock-movements/entities/stock-adjustment.entity';
import { StockAudit, StockAuditLine } from '../inventory/stock-movements/entities/stock-audit.entity';
import { StockTransfer, StockTransferLine } from '../inventory/stock-movements/entities/stock-transfer.entity';
import { PurchaseReceipt } from '../inventory/stock-movements/entities/purchase-receipt.entity';

// Sales
import { Quotation, QuotationLine } from '../sales/quotations/entities/quotation.entity';
import { SalesOrder, SalesOrderLine, DeliveryNote } from '../sales/sales-orders/entities/sales-order.entity';
import {
  SalesInvoice,
  SalesInvoiceLine,
  SalesReturn,
  SalesReturnLine,
} from '../sales/sales-invoices/entities/sales-invoice.entity';
import { SalesPayment } from '../sales/sales-payments/entities/sales-payment.entity';
import {
  InstallmentPlan,
  InstallmentPlanLine,
} from '../sales/installment-plans/entities/installment-plan.entity';
import { InstallmentScheduleItem } from '../sales/installment-plans/entities/installment-schedule-item.entity';
import { InstallmentPayment } from '../sales/installment-plans/entities/installment-payment.entity';

// HR — Employee/EmployeeLeave are staff master data and stay; only payroll/salary history clears.
import { PayrollRun, PayrollRunLine } from '../hr/entities/payroll-run.entity';

// Treasury — clearing CashMovement is what zeroes cash/bank/partner balances: every balance in
// this system is computed live from CashMovement rows, never stored as a running total, so
// nothing on Partner itself needs touching for its balance to read back as 0.
import { CashMovement } from '../treasury/entities/cash-movement.entity';
import { RecurringExpense } from '../treasury/entities/recurring-expense.entity';

// Imports — ShippingExpenseType is a category/master list and stays; the cargo/shipment
// transactions and their payments clear.
import { ImportCargoItem } from '../imports/entities/import-cargo-item.entity';
import { Shipment } from '../imports/entities/shipment.entity';
import { ShipmentExpense } from '../imports/entities/shipment-expense.entity';
import { ShipmentPayment } from '../imports/entities/shipment-payment.entity';

// Notifications generated by now-deleted transactions (e.g. installment reminders).
import { WhatsAppOutboxMessage } from '../whatsapp/entities/whatsapp-outbox-message.entity';

// Audit trail generated by demo usage — cleared along with the data it describes.
import { AuditLog } from '../audit-log/entities/audit-log.entity';

/**
 * Every table a factory reset clears — inventory movements/balances, sales & purchasing
 * transactions, quotations, receipts/vouchers, treasury/payroll/installment history, and
 * recurring expenses. Deliberately excludes every stakeholder & catalog master record (Customer,
 * Supplier, SalesRepresentative, CommissionException, Employee, EmployeeLeave, Product,
 * ProductBatch's catalog parent, Warehouse, Partner), every configuration table (Company, Branch,
 * Currency, ExchangeRate, Tax, FiscalYear, ProductCategory, Brand, Unit, PackageType,
 * ExpenseCategory, ShippingExpenseType), and every login (User, Role, Permission, Session,
 * UserCompany) — only NumberingSeries is touched, and only its running counter (see
 * factoryReset() below), never the series definition itself. A DB-level foreign-key audit
 * confirmed none of the preserved tables hold an FK pointing at any table in this list, so
 * `TRUNCATE ... CASCADE` cannot silently sweep a preserved table in via cascade.
 */
const TRANSACTIONAL_ENTITIES: EntityTarget<ObjectLiteral>[] = [
  SupplierPayment,
  ProductBatch,
  StockLevel,
  StockMovement,
  StockAdjustment,
  StockAdjustmentLine,
  StockAudit,
  StockAuditLine,
  StockTransfer,
  StockTransferLine,
  PurchaseReceipt,
  Quotation,
  QuotationLine,
  SalesOrder,
  SalesOrderLine,
  DeliveryNote,
  SalesInvoice,
  SalesInvoiceLine,
  SalesReturn,
  SalesReturnLine,
  SalesPayment,
  InstallmentPlan,
  InstallmentPlanLine,
  InstallmentScheduleItem,
  InstallmentPayment,
  PayrollRun,
  PayrollRunLine,
  CashMovement,
  RecurringExpense,
  ImportCargoItem,
  Shipment,
  ShipmentExpense,
  ShipmentPayment,
  WhatsAppOutboxMessage,
  AuditLog,
];

@Injectable()
export class SystemService {
  constructor(
    @InjectDataSource() private readonly dataSource: DataSource,
    @InjectRepository(User) private readonly userRepo: Repository<User>,
  ) {}

  /**
   * Wipes every inventory/sales/purchasing/treasury/payroll transaction back to empty in one
   * transaction, keeping every stakeholder & catalog master record, configuration table, and
   * login untouched (see TRANSACTIONAL_ENTITIES above for the exact boundary). TRUNCATE ...
   * CASCADE resolves foreign-key ordering automatically, so TRANSACTIONAL_ENTITIES doesn't need
   * to be dependency-sorted by hand — and since it's a single statement inside one
   * dataSource.transaction(), every table listed either clears together or (on any error) none
   * of them do, so a reset can never leave the data half-cleared. This also affects the whole
   * database, not just the caller's active company — deliberately: this reset has no per-company
   * scope, it's a full-instance calibration wipe available only to the Administrator role.
   *
   * Gated by two layers:
   *  1. @Permissions('system.delete') on the controller (global RBAC — only Administrator has it).
   *  2. Here: the caller's role is re-checked directly against isSystemRole, so a factory reset
   *     can never succeed just because *some* role was later granted the permission string — it
   *     must be the actual protected Administrator/Super-Admin role.
   *
   * Confirmation step: a fixed reset code ('0145'), checked directly rather than against the
   * caller's real account password/argon2 hash — an explicit, deliberate choice made after being
   * warned this means anyone who reads this source knows the code for every deployment, forever,
   * independent of any admin's real password or its rotation. Do not "fix" this back to real
   * password verification without the same conversation happening again.
   */
  async factoryReset(userId: string, resetCode: string): Promise<{ success: true; clearedTables: string[] }> {
    const RESET_CODE = '0145';

    const user = await this.userRepo.findOne({ where: { id: userId }, relations: ['roles'] });
    if (!user) throw new UnauthorizedException('User not found');

    const isSuperAdmin = user.roles?.some((role) => role.isSystemRole);
    if (!isSuperAdmin) {
      throw new ForbiddenException('Only the Administrator / Super Admin role can perform a factory reset');
    }

    if (resetCode !== RESET_CODE) {
      throw new UnauthorizedException('Incorrect reset code');
    }

    return this.dataSource.transaction(async (manager) => {
      const tableNames = TRANSACTIONAL_ENTITIES.map(
        (entity) => manager.getRepository(entity).metadata.tableName,
      );
      const quotedNames = tableNames.map((name) => `"${name}"`).join(', ');
      await manager.query(`TRUNCATE TABLE ${quotedNames} RESTART IDENTITY CASCADE`);

      // Numbering series definitions (prefix/padding/reset period) stay — only the running
      // counter restarts, so the next document recorded after a reset really is number 1 again.
      const seriesRepo = manager.getRepository(NumberingSeries);
      const allSeries = await seriesRepo.find();
      for (const series of allSeries) {
        series.nextNumber = series.startNumber ?? 1;
        series.lastResetKey = null;
      }
      if (allSeries.length) await seriesRepo.save(allSeries);

      return { success: true as const, clearedTables: tableNames };
    });
  }
}
